### ISSUE TITLE
URL for McQuillen Interactive  in the README is incorrect 

### ISSUE THREAD

**Issue by ciyer** [ScienceCommunicationLab/KinesinLMS#17]
**Describe the bug**

Click on the URL to McQuillen Interactive in the README, and you will see that does not resolve because of a typo (a missing 'c').

Changing the URL to https://mcquilleninteractive.com will fix it.

(I would make a PR, but forking, etc, seem like more overhead that is justified by such a small issue.)

**Comment by danielmcquillen** [comment]
Thanks @ciyer ! Fixed.
